Repository openshift/agent-installer-utils, pull requests merged in 2023-02, with the labels that each got.

#5 AGENT-532: Add integration tests
  go.mod
  go.sum
  hack/go-test.sh
  images/Containerfile.gotools
  images/Containerfile.gotools-local
  tools/agent_tui/app.go
  tools/agent_tui/app_test.go
  tools/agent_tui/apptester_test.go
  tools/agent_tui/main/main.go
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/common.go
  vendor/github.com/davecgh/go-spew/spew/config.go
  vendor/github.com/davecgh/go-spew/spew/doc.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/spew.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/gopkg.in/yaml.v3/LICENSE
  vendor/gopkg.in/yaml.v3/NOTICE
  vendor/gopkg.in/yaml.v3/README.md
  vendor/gopkg.in/yaml.v3/apic.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/gopkg.in/yaml.v3/readerc.go
  vendor/gopkg.in/yaml.v3/resolve.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/sorter.go
  vendor/gopkg.in/yaml.v3/writerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/gopkg.in/yaml.v3/yamlh.go
  vendor/gopkg.in/yaml.v3/yamlprivateh.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#4 AGENT-456 Add debugging information for failed connectivity checks
  go.mod
  go.sum
  tools/agent_tui/README.md
  tools/agent_tui/app.go
  tools/agent_tui/app_test.go
  tools/agent_tui/apptester_test.go
  tools/agent_tui/checks/engine.go
  tools/agent_tui/checks/url_parser.go
  tools/agent_tui/checks/url_parser_test.go
  tools/agent_tui/forms/node0.go
  tools/agent_tui/forms/regnode.go
  tools/agent_tui/main/main.go
  tools/agent_tui/net/net.go
  tools/agent_tui/net/validations.go
  tools/agent_tui/newt/colors.go
  tools/agent_tui/ui/check_page.go
  tools/agent_tui/ui/controller.go
  tools/agent_tui/ui/netstate_modal.go
  tools/agent_tui/ui/netstate_treeview.go
  tools/agent_tui/ui/nmtui.go
  tools/agent_tui/ui/timeout_modal.go
  tools/agent_tui/ui/ui.go
  vendor/github.com/sirupsen/logrus/.gitignore
  vendor/github.com/sirupsen/logrus/.golangci.yml
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/CHANGELOG.md
  vendor/github.com/sirupsen/logrus/LICENSE
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/appveyor.yml
  vendor/github.com/sirupsen/logrus/buffer_pool.go
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/hooks.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_js.go
  vendor/github.com/sirupsen/logrus/terminal_check_no_terminal.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_solaris.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/terminal_check_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
  vendor/modules.txt
Labels: approved, lgtm

#7 Change timeout dialog background and text color
  tools/agent_tui/ui/timeout_modal.go
Labels: approved, lgtm

#8 Adopt speaking method names and use atomic.Bool for thread safety
  tools/agent_tui/ui/check_page.go
  tools/agent_tui/ui/controller.go
  tools/agent_tui/ui/timeout_modal.go
  tools/agent_tui/ui/ui.go
Labels: approved, lgtm

#10 OCPBUGS-7731: Fix cancel user prompt
  tools/agent_tui/app.go
  tools/agent_tui/checks/engine.go
  tools/agent_tui/ui/check_page.go
  tools/agent_tui/ui/controller.go
  tools/agent_tui/ui/nmtui.go
  tools/agent_tui/ui/splashcreen.go
  tools/agent_tui/ui/timeout_modal.go
  tools/agent_tui/ui/ui.go
Labels: approved, jira/valid-bug, bugzilla/valid-bug, lgtm, jira/valid-reference

#11 revert to golang 1.18
  tools/agent_tui/ui/ui.go
Labels: approved, lgtm

#12 skipping ping check for registry ci
  tools/agent_tui/app.go
  tools/agent_tui/app_test.go
  tools/agent_tui/checks/engine.go
  tools/agent_tui/ui/check_page.go
Labels: approved, lgtm

#13 skipping pings by regexp, to match all possible ci registries
  tools/agent_tui/app.go
Labels: approved, lgtm
