Repository openshift/agent-installer-utils, pull requests merged in 2025-05, with the labels that each got.

#81 OCPBUGS-55623: update to go.mod
  go.mod
Labels: approved, jira/valid-bug, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#80 OCPBUGS-55515: Include cnv operator in ISO builder script
  tools/iso_builder/hack/build-ove-image.sh
Labels: approved, jira/valid-bug, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#79 NO-ISSUE: ISOBuilder: Add support for default CatalogSource naming
  tools/iso_builder/hack/build-ove-image.sh
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#83 NO-ISSUE: Update ISOBuilder appliance image SHA
  tools/iso_builder/hack/build-ove-image.sh
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#84 OCPBUGS-55708: Include RHEL 9 guest image to support VM launches via …
  tools/iso_builder/hack/build-ove-image.sh
Labels: approved, jira/valid-bug, lgtm, jira/valid-reference

#86 AGENT-1195: bump appliance image to 4042ba
  tools/iso_builder/hack/build-ove-image.sh
Labels: approved, lgtm, jira/valid-reference

#78 OCPBUGS-55769: Use internal image registry
  tools/iso_builder/hack/build-ove-image.sh
Labels: approved, jira/valid-bug, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#89 OCPBUGS-56112: configure the channel for each OLM operators
  tools/iso_builder/hack/build-ove-image.sh
Labels: approved, jira/valid-bug, lgtm, jira/valid-reference

#91 OCPBUGS-56210: OVE builder: Remove RHEL9 image from additionalImages
  tools/iso_builder/hack/build-ove-image.sh
Labels: approved, jira/valid-bug, lgtm, jira/valid-reference

#93 OCPBUGS-56223: Fix nmtui redirection after quit
  tools/agent_tui/ui/rendezvous_ip_connectivity_fail_modal.go
  tools/agent_tui/ui/rendezvous_ip_save_success_modal.go
  tools/agent_tui/ui/rendezvous_ip_select.go
  tools/agent_tui/ui/rendezvous_modal.go
Labels: approved, jira/valid-bug, lgtm, jira/severity-critical, jira/valid-reference

#101 OCPBUGS-56880: Log error from nmtui and change modal background
  tools/agent_tui/ui/nmtui.go
Labels: approved, jira/valid-bug, lgtm, jira/valid-reference
